name: Release

on:
  release:
    types: ["published"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get release tag
      run: |
        echo ${{github.ref_name}}
        echo "RELEASE_TAG=${{github.ref_name}}" >> $GITHUB_ENV
        
    - name: Read release tag
      run: echo $RELEASE_TAG
